-- DESIGN MIGRATION ONLY. Do not auto-apply. PostgreSQL 16 target (verify in deployment).
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN CREATE TYPE consent_state_v3 AS ENUM ('DRAFT','PENDING','APPROVED','REJECTED','EXPIRED','REVOKED','SUPERSEDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE ticket_state_v3 AS ENUM ('CREATED','ISSUED','SCANNED','PATIENT_APPROVED','AUTHORIZED','CONSUMED','EXPIRED','REVOKED','REPLAY_BLOCKED','REJECTED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE package_state_v3 AS ENUM ('CREATED','ENCRYPTED','DOWNLOADING','STORED_ON_DEVICE','READY_FOR_HANDOFF','HANDOFF_PENDING','UPLOADING','RECEIVED','VERIFIED','VIEWED','IMPORTED','EXPIRED','REVOKED','DELETED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS institutions (institution_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, display_name text NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','SUSPENDED','REVOKED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), oidc_issuer text NOT NULL, oidc_subject text NOT NULL, status text NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(oidc_issuer,oidc_subject));
CREATE TABLE IF NOT EXISTS user_institution_roles (user_id uuid NOT NULL REFERENCES users(user_id), institution_id uuid NOT NULL REFERENCES institutions(institution_id), role text NOT NULL, valid_until timestamptz, PRIMARY KEY(user_id,institution_id,role));
CREATE TABLE IF NOT EXISTS patient_identity_refs (patient_ref uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), protected_local_ref bytea NOT NULL, local_ref_digest bytea NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(institution_id,local_ref_digest));
CREATE TABLE IF NOT EXISTS mobile_devices (device_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), patient_ref uuid NOT NULL REFERENCES patient_identity_refs(patient_ref), institution_id uuid NOT NULL REFERENCES institutions(institution_id), platform text NOT NULL CHECK(platform IN ('ANDROID','IOS')), app_version text NOT NULL, status text NOT NULL CHECK(status IN ('PENDING','ACTIVE','BLOCKED','LOST','REVOKED')), risk_level text NOT NULL DEFAULT 'UNKNOWN', last_seen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS device_keys (device_key_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), device_id uuid NOT NULL REFERENCES mobile_devices(device_id), key_version integer NOT NULL CHECK(key_version>0), public_jwk jsonb NOT NULL, attestation_digest bytea NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','REVOKED','DESTROYED')), created_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, UNIQUE(device_id,key_version));
CREATE TABLE IF NOT EXISTS consents_v3 (consent_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), patient_ref uuid NOT NULL REFERENCES patient_identity_refs(patient_ref), source_institution_id uuid NOT NULL REFERENCES institutions(institution_id), target_institution_id uuid NOT NULL REFERENCES institutions(institution_id), purpose text NOT NULL, status consent_state_v3 NOT NULL DEFAULT 'DRAFT', action_scopes text[] NOT NULL, valid_from timestamptz NOT NULL, valid_until timestamptz NOT NULL, policy_version text NOT NULL, version integer NOT NULL DEFAULT 1, evidence_digest bytea, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, CHECK(valid_until>valid_from));
CREATE TABLE IF NOT EXISTS consent_scopes_v3 (scope_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), consent_id uuid NOT NULL REFERENCES consents_v3(consent_id) ON DELETE RESTRICT, study_ref text NOT NULL, series_ref text, instance_ref text, frame_start integer, frame_end integer, created_at timestamptz NOT NULL DEFAULT now(), CHECK((frame_start IS NULL AND frame_end IS NULL) OR (frame_start>=1 AND frame_end>=frame_start)), UNIQUE NULLS NOT DISTINCT(consent_id,study_ref,series_ref,instance_ref,frame_start,frame_end));
CREATE TABLE IF NOT EXISTS transfer_requests (transfer_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), consent_id uuid NOT NULL REFERENCES consents_v3(consent_id), requester_user_id uuid NOT NULL REFERENCES users(user_id), source_institution_id uuid NOT NULL REFERENCES institutions(institution_id), target_institution_id uuid NOT NULL REFERENCES institutions(institution_id), purpose text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS imaging_packages (package_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transfer_id uuid NOT NULL REFERENCES transfer_requests(transfer_id), device_id uuid REFERENCES mobile_devices(device_id), status package_state_v3 NOT NULL DEFAULT 'CREATED', object_uri text, total_size bigint CHECK(total_size>=0), expires_at timestamptz NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS package_manifests (manifest_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES imaging_packages(package_id), schema_version text NOT NULL, canonical_hash bytea NOT NULL, instance_count integer NOT NULL CHECK(instance_count>=0), frame_count bigint NOT NULL CHECK(frame_count>=0), scope_json jsonb NOT NULL, encrypted_object_uri text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(package_id));
CREATE TABLE IF NOT EXISTS package_chunks (package_id uuid NOT NULL REFERENCES imaging_packages(package_id), chunk_no integer NOT NULL CHECK(chunk_no>=0), size_bytes bigint NOT NULL CHECK(size_bytes>0), cipher_hash bytea NOT NULL, status text NOT NULL, received_at timestamptz, PRIMARY KEY(package_id,chunk_no));
CREATE TABLE IF NOT EXISTS key_envelopes (envelope_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES imaging_packages(package_id), recipient_type text NOT NULL CHECK(recipient_type IN ('MOBILE_DEVICE','B_GATEWAY','KMS_ESCROW')), recipient_ref text NOT NULL, kms_key_ref text NOT NULL, wrapped_dek bytea NOT NULL, algorithm text NOT NULL, key_version integer NOT NULL CHECK(key_version>0), status text NOT NULL CHECK(status IN ('ACTIVE','DISABLED','DESTROYED')), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, destroyed_at timestamptz, UNIQUE(package_id,recipient_type,recipient_ref,key_version));
CREATE TABLE IF NOT EXISTS handoff_sessions (handoff_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transfer_id uuid NOT NULL REFERENCES transfer_requests(transfer_id), target_institution_id uuid NOT NULL REFERENCES institutions(institution_id), clinician_user_id uuid NOT NULL REFERENCES users(user_id), gateway_ref text NOT NULL, purpose text NOT NULL, status ticket_state_v3 NOT NULL DEFAULT 'CREATED', expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS handoff_tickets (ticket_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), handoff_id uuid NOT NULL REFERENCES handoff_sessions(handoff_id), token_hash bytea NOT NULL UNIQUE, jti text NOT NULL UNIQUE, status ticket_state_v3 NOT NULL DEFAULT 'CREATED', issued_at timestamptz, expires_at timestamptz NOT NULL, used_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS remote_access_sessions (session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), consent_id uuid NOT NULL REFERENCES consents_v3(consent_id), user_id uuid NOT NULL REFERENCES users(user_id), institution_id uuid NOT NULL REFERENCES institutions(institution_id), token_hash bytea NOT NULL UNIQUE, jti text NOT NULL UNIQUE, scope_json jsonb NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS pacs_imports (import_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES imaging_packages(package_id), target_institution_id uuid NOT NULL REFERENCES institutions(institution_id), protocol text NOT NULL CHECK(protocol IN ('STOW_RS','C_STORE')), idempotency_key text NOT NULL, status text NOT NULL, receipt_json jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(target_institution_id,idempotency_key));
CREATE TABLE IF NOT EXISTS delivery_receipts (receipt_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES imaging_packages(package_id), handoff_id uuid NOT NULL REFERENCES handoff_sessions(handoff_id), manifest_hash bytea NOT NULL, receiver_institution_id uuid NOT NULL REFERENCES institutions(institution_id), result text NOT NULL, signature bytea NOT NULL, received_at timestamptz NOT NULL, UNIQUE(package_id,handoff_id,result));
CREATE TABLE IF NOT EXISTS revocations (revocation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), object_type text NOT NULL, object_id uuid NOT NULL, reason_code text NOT NULL, actor_user_id uuid REFERENCES users(user_id), revoked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS deletion_receipts (deletion_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), object_type text NOT NULL, object_id uuid NOT NULL, method text NOT NULL, result text NOT NULL, requested_at timestamptz NOT NULL, completed_at timestamptz, evidence_digest bytea);
CREATE TABLE IF NOT EXISTS policy_decisions (decision_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), action text NOT NULL, decision text NOT NULL CHECK(decision IN ('ALLOW','DENY')), reason_code text NOT NULL, context_digest bytea NOT NULL, policy_version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS gateway_registrations (gateway_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), workload_subject text NOT NULL UNIQUE, certificate_fingerprint bytea NOT NULL UNIQUE, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS temporary_cache_objects (cache_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid NOT NULL REFERENCES institutions(institution_id), package_id uuid REFERENCES imaging_packages(package_id), encrypted_object_uri text NOT NULL, status text NOT NULL, expires_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS outbox_events (event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz);
CREATE TABLE IF NOT EXISTS idempotency_keys (institution_id uuid NOT NULL REFERENCES institutions(institution_id), actor_ref text NOT NULL, endpoint text NOT NULL, idempotency_key text NOT NULL, request_digest bytea NOT NULL, response_status integer, response_body jsonb, expires_at timestamptz NOT NULL, PRIMARY KEY(institution_id,actor_ref,endpoint,idempotency_key));
CREATE TABLE IF NOT EXISTS error_events (error_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid REFERENCES institutions(institution_id), request_id text NOT NULL, trace_id text, audit_session_id text, safe_code text NOT NULL, component text NOT NULL, retryable boolean NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs_v3 (event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), institution_id uuid REFERENCES institutions(institution_id), audit_session_id text NOT NULL, event_type text NOT NULL, actor_ref text NOT NULL, patient_ref uuid REFERENCES patient_identity_refs(patient_ref), consent_id uuid REFERENCES consents_v3(consent_id), package_id uuid REFERENCES imaging_packages(package_id), device_id uuid REFERENCES mobile_devices(device_id), action text NOT NULL, decision text NOT NULL, reason_code text, trace_id text, event_time timestamptz NOT NULL, previous_hash bytea, record_hash bytea NOT NULL);

CREATE INDEX IF NOT EXISTS idx_consent_v3_eval ON consents_v3(target_institution_id,patient_ref,status,valid_until);
CREATE INDEX IF NOT EXISTS idx_package_status_expiry ON imaging_packages(status,expires_at) WHERE status NOT IN ('DELETED','FAILED');
CREATE INDEX IF NOT EXISTS idx_ticket_hash ON handoff_tickets(token_hash);
CREATE INDEX IF NOT EXISTS idx_ticket_expiry ON handoff_tickets(status,expires_at) WHERE status IN ('CREATED','ISSUED','SCANNED','PATIENT_APPROVED','AUTHORIZED');
CREATE INDEX IF NOT EXISTS idx_handoff_target_status ON handoff_sessions(target_institution_id,status,expires_at);
CREATE INDEX IF NOT EXISTS idx_remote_token_expiry ON remote_access_sessions(token_hash,expires_at) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_cache_expiry ON temporary_cache_objects(status,expires_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_audit_v3_search ON audit_logs_v3(institution_id,event_time DESC,event_type);
CREATE INDEX IF NOT EXISTS idx_error_code_time ON error_events(safe_code,created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at_v3() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['institutions','users','mobile_devices','consents_v3','transfer_requests','imaging_packages','handoff_sessions','pacs_imports'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated ON %I',t,t); EXECUTE format('CREATE TRIGGER trg_%I_updated BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at_v3()',t,t); END LOOP; END $$;

ALTER TABLE mobile_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE consents_v3 ENABLE ROW LEVEL SECURITY;
ALTER TABLE imaging_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE handoff_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs_v3 ENABLE ROW LEVEL SECURITY;
-- Application transaction must SET LOCAL app.institution_id to a validated UUID.
DROP POLICY IF EXISTS tenant_mobile_devices ON mobile_devices;
DROP POLICY IF EXISTS tenant_consents ON consents_v3;
DROP POLICY IF EXISTS tenant_handoffs ON handoff_sessions;
DROP POLICY IF EXISTS tenant_audit ON audit_logs_v3;
DROP POLICY IF EXISTS tenant_packages ON imaging_packages;
CREATE POLICY tenant_mobile_devices ON mobile_devices USING (institution_id = nullif(current_setting('app.institution_id',true),'')::uuid);
CREATE POLICY tenant_consents ON consents_v3 USING (source_institution_id = nullif(current_setting('app.institution_id',true),'')::uuid OR target_institution_id = nullif(current_setting('app.institution_id',true),'')::uuid);
CREATE POLICY tenant_handoffs ON handoff_sessions USING (target_institution_id = nullif(current_setting('app.institution_id',true),'')::uuid);
CREATE POLICY tenant_audit ON audit_logs_v3 USING (institution_id = nullif(current_setting('app.institution_id',true),'')::uuid);
-- Imaging package tenant policy is mediated through transfer_requests.
CREATE POLICY tenant_packages ON imaging_packages USING (EXISTS (SELECT 1 FROM transfer_requests tr WHERE tr.transfer_id=imaging_packages.transfer_id AND (tr.source_institution_id=nullif(current_setting('app.institution_id',true),'')::uuid OR tr.target_institution_id=nullif(current_setting('app.institution_id',true),'')::uuid)));

-- Existing status mapping: ACTIVE->APPROVED, REVOKED->REVOKED; expired ACTIVE is evaluated/migrated as EXPIRED.
-- Existing dicom_access_token_logs.token must be backfilled to token_hash in a separate reviewed migration, then plaintext removed.
COMMIT;
