FROM jodogne/orthanc-plugins:1.12.11

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && mkdir -p /tmp/orthanc-required-plugins \
    && cp /usr/local/share/orthanc/plugins/libOrthancDicomWeb.so /tmp/orthanc-required-plugins/ \
    && rm -f /usr/local/share/orthanc/plugins/*.so \
    && cp /tmp/orthanc-required-plugins/*.so /usr/local/share/orthanc/plugins/ \
    && rm -rf /tmp/orthanc-required-plugins \
    && apt-get purge -y libglib2.0-0 libglib2.0-data libsqlite3-0 libxml2 \
    && apt-get purge -y openssl libssl3 wget mount \
    && apt-get autoremove -y --purge \
    && apt-get purge -y --allow-remove-essential gzip ncurses-base ncurses-bin bsdutils util-linux \
    && apt-get autoremove -y --purge \
    && apt-get purge -y --allow-remove-essential perl-base \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/perl /usr/lib/*/perl /usr/local/lib/*/perl /usr/share/doc/* /usr/share/man/*
